server:
  port: 8080
  tomcat:
    threads:
      max: 200
    max-connections: 10000
    accept-count: 100
    connection-timeout: 5000

spring:
  application:
    name: chartink-webhook
  webflux:
    base-path: /api

telegram:
  bot:
    token: "8199254732:AAEn-4X-z87-pSp1SKcJEjJjoyewXvOxmfg"
  chat:
    id: "-1002511791814"

logging:
  level:
    com.chartink.webhook: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name} 